import React from "react";
import { apiGet, apiPatch, apiPost } from "../api";
type Props={projectId:string;token:string};
type Item={id:string;procurement_item_id?:string|null;item_code?:string|null;material_name:string;specification?:string|null;unit?:string|null;opening_quantity?:number|null;received_quantity?:number|null;consumed_quantity?:number|null;reserved_quantity?:number|null;reorder_level?:number|null;supplier?:string|null;location?:string|null};
export function InventoryCenter({projectId,token}:Props){
 const[items,setItems]=React.useState<Item[]>([]),[busy,setBusy]=React.useState(false),[error,setError]=React.useState(""),[notice,setNotice]=React.useState(""),[editingId,setEditingId]=React.useState<string|null>(null),[edit,setEdit]=React.useState<Partial<Item>>({});
 async function load(){setBusy(true);setError("");try{const r=await apiGet("/api/v1/projects/"+projectId+"/inventory/items",token);setItems(r.data||[])}catch(e:any){setError(e.message||"Could not load inventory.")}finally{setBusy(false)}}
 async function save(){if(!editingId)return;setBusy(true);setError("");try{await apiPatch("/api/v1/projects/"+projectId+"/inventory/items/"+editingId,token,{opening_quantity:Number(edit.opening_quantity||0),consumed_quantity:Number(edit.consumed_quantity||0),reserved_quantity:Number(edit.reserved_quantity||0),reorder_level:Number(edit.reorder_level||0),location:edit.location||null});setNotice("Inventory item updated.");setEditingId(null);await load()}catch(e:any){setError(e.message||"Could not update inventory.")}finally{setBusy(false)}}
 async function issue(i:Item){const raw=window.prompt("Quantity consumed / issued for "+i.material_name+":","0");if(raw===null)return;const qty=Number(raw);if(!Number.isFinite(qty)||qty<=0){setError("Enter a positive quantity.");return}setBusy(true);setError("");try{await apiPost("/api/v1/projects/"+projectId+"/inventory/items/"+i.id+"/issue",token,{quantity:qty,notes:"Site material consumption"});setNotice(qty+" "+(i.unit||"units")+" issued from "+i.material_name+".");await load()}catch(e:any){setError(e.message||"Could not issue inventory.")}finally{setBusy(false)}}
 React.useEffect(()=>{load()},[projectId,token]);
 const received=items.reduce((s,i)=>s+Number(i.received_quantity||0),0),consumed=items.reduce((s,i)=>s+Number(i.consumed_quantity||0),0),low=items.filter(i=>Number(i.opening_quantity||0)+Number(i.received_quantity||0)-Number(i.consumed_quantity||0)-Number(i.reserved_quantity||0)<=Number(i.reorder_level||0)).length;
 return <section className="panel"><div className="panel-head"><div><h2>Inventory Center</h2><p className="muted small">Material stock, receipts, consumption and reorder visibility.</p></div><button className="button compact" disabled={busy} onClick={load}>Refresh</button></div>
 {error&&<div className="error">{error}</div>}{notice&&<div className="success">{notice}</div>}
 <div className="center-summary"><div className="hint"><b>Materials</b><span> · {items.length}</span></div><div className="hint"><b>Received</b><span> · {received.toLocaleString()}</span></div><div className="hint"><b>Consumed</b><span> · {consumed.toLocaleString()}</span></div><div className="hint"><b>Reorder alerts</b><span> · {low}</span></div></div>
 {busy&&!items.length?<p className="muted">Loading…</p>:items.length?<div className="table-wrap"><table><thead><tr><th>Code</th><th>Material</th><th>Opening</th><th>Received</th><th>Consumed</th><th>Reserved</th><th>Available</th><th>Reorder</th><th>Location</th><th>Action</th></tr></thead><tbody>{items.map(i=>{const available=Number(i.opening_quantity||0)+Number(i.received_quantity||0)-Number(i.consumed_quantity||0)-Number(i.reserved_quantity||0);return <tr key={i.id}><td>{i.item_code||"—"}</td><td><b>{i.material_name}</b><br/><small>{i.specification||"No specification"}</small></td>{editingId===i.id?<><td><input type="number" min="0" value={Number(edit.opening_quantity||0)} onChange={e=>setEdit({...edit,opening_quantity:Number(e.target.value)})}/></td><td>{Number(i.received_quantity||0).toLocaleString()}</td><td><input type="number" min="0" value={Number(edit.consumed_quantity||0)} onChange={e=>setEdit({...edit,consumed_quantity:Number(e.target.value)})}/></td><td><input type="number" min="0" value={Number(edit.reserved_quantity||0)} onChange={e=>setEdit({...edit,reserved_quantity:Number(e.target.value)})}/></td><td>{available.toLocaleString()} {i.unit||""}</td><td><input type="number" min="0" value={Number(edit.reorder_level||0)} onChange={e=>setEdit({...edit,reorder_level:Number(e.target.value)})}/></td><td><input value={edit.location||""} onChange={e=>setEdit({...edit,location:e.target.value})}/></td><td><button className="button compact" disabled={busy} onClick={save}>Save</button> <button className="button compact" onClick={()=>setEditingId(null)}>Cancel</button></td></>:<><td>{Number(i.opening_quantity||0).toLocaleString()}</td><td>{Number(i.received_quantity||0).toLocaleString()}</td><td>{Number(i.consumed_quantity||0).toLocaleString()}</td><td>{Number(i.reserved_quantity||0).toLocaleString()}</td><td><b>{available.toLocaleString()}</b> {i.unit||""}</td><td>{Number(i.reorder_level||0).toLocaleString()}</td><td>{i.location||"—"}</td><td><button className="button compact" disabled={busy} onClick={()=>{setEditingId(i.id);setEdit({...i})}}>Update</button> <button className="button compact" disabled={busy||available<=0} onClick={()=>issue(i)}>Issue</button></td></>}</tr>})}</tbody></table></div>:<div className="empty"><p>No inventory items yet. Delivered procurement items will appear here automatically.</p></div>}</section>;
}